import LocalizedStrings from 'react-localization';

export const localizedStrings = new LocalizedStrings({
    en:  {
        newsPortal: "News Portal",
        logout: "Logout",
        login: "Login",
        signUp: "Sign up",
        password: "Password",
        loginField: "Login",
        name: "Name",
        surname: "Surname",
        confirmedPassword: "Confirmed password",
        hello: "Hello, ",
        logIn: "Log in",
        createAccount: "Create Account",
        haveAccount: "Have an account?",
        fillInForm: "Fill in the form",
        older: "Older",
        newer: "Newer",
        close: "Close",
        edit: "Edit",
        delete: "Delete",
        dashboard: "Dashboard",
        editAuthor: "Create/Edit authors",
        editTags: "Create/Edit tags",
        editNews: "Create news",
        signIn: "Sign In",
        save: "Save",
        title: "Title",
        shortText: "Short Text",
        fullText: "Full Text",
        add: "Add",
        search: "Search",
        reset: "Reset",
        searchByAuthor: "Search by Author",
        searchByTag: "Search by Tag"
    },
    ru: {
        newsPortal: "Новостной портал",
        logout: "Выйти",
        login: "Войти",
        logIn: "Войти",
        signUp: "Зарегистрироваться",
        password: "Пароль",
        loginField: "Логин",
        name: "Имя",
        surname: "Фамилия",
        confirmedPassword: "Подтвердите пароль",
        hello: "Приветсвуем, ",
        createAccount: "Создать профиль",
        haveAccount: "Имеете аккаунт?",
        fillInForm: "Заполните поля",
        older: "Раньше",
        newer: "Позже",
        close: "Закрыть",
        edit: "Редактировать",
        delete: "Удалить",
        dashboard: "Меню",
        editAuthor: "Создать авторов",
        editTags: "Создать теги",
        editNews: "Cоздать новость",
        signIn: "Войти",
        save: "Сохранить",
        title: "Заголовок",
        shortText: "Короткое описание",
        fullText: "Полный текст",
        add: "Добавить",
        search: "Поиск",
        reset: "Отмена",
        searchByAuthor: "Искать по автору",
        searchByTag: "Искать по тегу"
    }

});